services:
  prod:
    build:
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 8080:5000
    profiles: [prod]

  dev:
    build:
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - 8080:5000
    volumes:
      - .:/home/node/app
    profiles: [dev]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  postgres:
    image: "postgres:alpine"
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: change-me

volumes:
  postgres_data:
