services:
  prod:
    build:
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_started
    profiles: [prod]

  dev:
    build:
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      postgres:
        condition: service_started
    profiles: [dev]

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: "postgres:alpine"
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ".env"

volumes:
  postgres_data:
