services:
  web:
    build: .
    restart: always
    ports:
      - 8080:5000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  postgres:
    image: "postgres:alpine"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: change-me
